version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile 
    ports:
      - '80:80'
  web:
    build: 
      context: .
      dockerfile: httpd.Dockerfile
    volumes:
      - ./html:/usr/local/apache2/htdocs/