# create your drupal and postgres config here, based off the last assignment
version: "2"
services:
  drupal:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    image: custom-drupal  
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/themes
      - drupal-themes:/var/www/html/sites
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes: 
      - drupal-data:/var/lib/postgresql/data  
volumes: 
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:  
